### ISSUE TITLE
Create Time Class

### ISSUE THREAD

**Issue by MaraJade** [osuosl/timesync-frontend-django#3]
Create a Time Class that includes methods for reporting time

**Comment by matthewrsj** [comment]
Let's call it a `timesync` class since it will also include methods for viewing, updating, etc.

**Comment by matthewrsj** [comment]
@Kennric @MaraJade where should the module go in the Django structure? `/timesync_frontend/`?

**Comment by matthewrsj** [comment]
This is being moved to https://github.com/osuosl/python-timesync/issues/1
